db:
  username: postgres
  password: admin
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost, 127.0.0.1
  properties:
    first: 1
    last: 2
    key: value
  pool:
    size: 10
    timeout: 20
  pools:
    - size: 11
      timeout: 20
    - size: 12
      timeout: 20
    - size: 13
      timeout: 20

logging:
  level:
    root: warn
    by.bnd.spring.database.repository.pool: info
  file:
    name: by.bnd
    path: /
